github: Spacecer2
# ko_fi: replace-with-your-ko-fi-username
# patreon: replace-with-your-patreon-username
# open_collective: replace-with-your-open-collective
# custom: ['https://buymeacoffee.com/YOUR_USERNAME']
