#!/usr/bin/env bash
#
# generate-hyprglass-from-wallust.sh
# Generates HyprGlass config snippet from wallust colors.
#
# Reads wallust-hyprland.conf, extracts $color12 and $background,
# calculates brightness, and writes wallust-generated.conf
#

set -euo pipefail

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
WALLUST_CONF="${HOME}/.config/hypr/wallust/wallust-hyprland.conf"
OUTPUT_CONF="${PROJECT_DIR}/wallust-generated.conf"

# Fallback for wallust config location
if [[ ! -f "$WALLUST_CONF" ]]; then
    WALLUST_CONF="${HOME}/.config/hyprland/wallust-hyprland.conf"
fi

if [[ ! -f "$WALLUST_CONF" ]]; then
    echo "Error: wallust-hyprland.conf not found" >&2
    exit 1
fi

# Extract color values (strip # prefix)
get_color() {
    local var="$1"
    grep -E "^\s*${var}=" "$WALLUST_CONF" | head -1 | sed 's/.*= *#//' | sed 's/\s*$//'
}

color12=$(get_color "color12")
background=$(get_color "background")

if [[ -z "$color12" || -z "$background" ]]; then
    echo "Error: Could not extract color12 or background" >&2
    exit 1
fi

# Convert hex to RGB components
hex_to_rgb() {
    local hex="$1"
    echo "$((16#${hex:0:2})) $((16#${hex:2:2})) $((16#${hex:4:2}))"
}

# Calculate perceived brightness (0-255 scale)
calc_brightness() {
    local hex="$1"
    read -r r g b <<< "$(hex_to_rgb "$hex")"
    # ITU-R BT.709 luminance
    echo $(( (r * 299 + g * 587 + b * 114) / 1000 ))
}

bg_brightness=$(calc_brightness "$background")

# Determine brightness tier for HyprGlass
if (( bg_brightness < 50 )); then
    brightness_tier="dark"
    glass_opacity="0.85"
    glass_blur="true"
    text_color="rgb(f0f0f0)"
elif (( bg_brightness < 128 )); then
    brightness_tier="dim"
    glass_opacity="0.75"
    glass_blur="true"
    text_color="rgb(e0e0e0)"
elif (( bg_brightness < 200 )); then
    brightness_tier="medium"
    glass_opacity="0.65"
    glass_blur="true"
    text_color="rgb(202020)"
else
    brightness_tier="light"
    glass_opacity="0.55"
    glass_blur="true"
    text_color="rgb(1a1a1a)"
fi

# Generate config
cat > "$OUTPUT_CONF" << EOF
# HyprGlass color sync - auto-generated by wallust
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# Source: ${WALLUST_CONF}

# Wallpaper accent color
\$tint_color = rgb(${color12})
\$tint_color_alpha = rgba(${color12}aa)

# Background-based settings
\$background_color = rgb(${background})
\$bg_brightness = ${bg_brightness}
\$brightness_tier = ${brightness_tier}

# Glass appearance
\$glass_opacity = ${glass_opacity}
\$glass_blur = ${glass_blur}
\$text_color = ${text_color}

# Tint applied to HyprGlass surfaces
hyprglass_tint_color = \$tint_color
hyprglass_opacity = \$glass_opacity
hyprglass_blur = \$glass_blur
EOF

echo "Generated: ${OUTPUT_CONF}"
echo "  Accent: #${color12}"
echo "  Background: #${background} (brightness: ${bg_brightness}, tier: ${brightness_tier})"
